import React, { useEffect, useState } from 'react';
import { AutoCapture, ensureNightlySync, exportGoogleWalletDiagnostics, importCapturedTransactions, isAutoCaptureAvailable, syncCapturedTransactionsNow } from '../../services/autoCapture';
const buttonClass='w-full rounded-xl px-3 py-2.5 text-sm font-semibold transition active:scale-[0.99]';
const fmt=(ms)=>{if(!ms)return'—';const d=new Date(Number(ms));return`${d.getMonth()+1}/${d.getDate()} ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;};
const resultText=(v)=>v==='OK'?'成功':String(v||'').startsWith('TIMEOUT')?'逾時':v==='PENDING'?'等待中':v==='NOT_STARTED'?'未啟動':v==='NONE'?'—':v;
export default function AutoCapturePanel({darkMode}){
 const native=isAutoCaptureAvailable();const[status,setStatus]=useState(null);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');
 const refresh=async()=>{if(!native)return null;try{const s=await AutoCapture.getStatus();setStatus(s);return s;}catch(error){console.warn(error);return null;}};
 const autoImport=async()=>{if(!native)return;setBusy(true);try{const s=await AutoCapture.getStatus();setStatus(s);if(s?.unifiedSyncRunning){setMessage('同步尚未完成，請等四個支付來源全部結束。');return;}const merged=await importCapturedTransactions();await AutoCapture.recordImportResult({added:Number(merged?.added||0),matched:Number(merged?.matched||0),unmatched:Number(merged?.unmatched||0)}).catch(console.warn);const m=merged.added>0?`；已配對優惠 ${merged.matched} 筆${merged.unmatched?`，待確認 ${merged.unmatched} 筆`:''}`:'';setMessage(`已寫入 ${merged.added} 筆新交易到台灣消費紀錄${m}。`);if(merged.added>0){localStorage.setItem('country','TW');window.setTimeout(()=>window.location.reload(),400);}}catch(error){setMessage(`同步寫入失敗：${error?.message||error}`);}finally{setBusy(false);}};
 useEffect(()=>{if(!native)return;refresh();ensureNightlySync().catch(console.warn);const timer=window.setInterval(()=>{if(!document.hidden)refresh();},900);return()=>window.clearInterval(timer);},[native]);
 const instantSync=async()=>{setBusy(true);setMessage('即時同步已啟動：街口 → LINE Pay → Pi 拍錢包 → Google Pay。四個來源完成後會自動寫入並回首頁。');try{const merged=await syncCapturedTransactionsNow();if(merged.added>0)setMessage(`已先整理 ${merged.added} 筆既有交易；現在開始更新四個支付來源。`);}catch(error){const text=String(error?.message||error||'UNKNOWN');setMessage(text.includes('ACCESSIBILITY')?'請先開啟「Pay Helper 自動消費同步」無障礙服務。':text.includes('SYNC_ALREADY_RUNNING')?'目前已有同步正在進行中。':`即時同步啟動失敗：${text}`);}finally{setBusy(false);setTimeout(refresh,500);}};
 const exportGoogle=async()=>{setBusy(true);try{const result=await AutoCapture.getGoogleWalletDiagnostics();const captures=result.captures||[];if(!captures.length){setMessage('目前沒有 Google Wallet 診斷畫面。');return;}await exportGoogleWalletDiagnostics(captures);setMessage(`已建立 Google Wallet 診斷 JSON，共 ${captures.length} 個畫面。`);}catch(error){setMessage(`Google Wallet 診斷匯出失敗：${error?.message||error}`);}finally{setBusy(false);}};
 const card=darkMode?'bg-gray-800 border border-gray-700 text-white rounded-3xl shadow-xl p-4 mb-4':'bg-white border border-gray-200 text-gray-900 rounded-3xl shadow-xl p-4 mb-4';if(!native)return <div className={card}><div className="font-bold mb-1">自動消費同步</div><div className="text-xs opacity-60">此功能只在 Android APK 版啟用。</div></div>;
 const stages=['街口','LINE Pay','Pi 拍錢包','Google Pay','完成'];const night=status?.lastNightlyResult;const nightOk=night?.status==='SUCCESS';const nightWarn=night?.status==='PARTIAL';
 return <div className={card}><div className="flex items-center justify-between gap-2 mb-2"><div><div className="font-bold">即時同步（Android）</div><div className="text-[11px] opacity-60">四種支付交易記錄 → 比對信用卡優惠 → 自動寫入</div></div><span className={`px-2 py-1 rounded-full text-[10px] ${status?.accessibilityEnabled?'bg-green-500':'bg-amber-500'} text-white`}>{status?.accessibilityEnabled?'同步服務已開啟':'需開啟無障礙'}</span></div>
 <div className="grid grid-cols-2 gap-2 text-[11px] mb-3 opacity-70"><div>街口：{status?.jkoCount??0}</div><div>LINE Pay：{status?.linePayCount??0}</div><div>Pi：{status?.piWalletCount??0}</div><div>Google Pay：{status?.googleWalletCount??0}</div></div>
 {status?.unifiedSyncRunning&&<div className={`${darkMode?'bg-blue-950':'bg-blue-50'} rounded-xl p-3 text-xs mb-3`}>同步進行中：{stages[status?.unifiedSyncStage]||'處理中'}。每個來源都有 timeout，整輪另有 8 分鐘硬性上限。</div>}
 {status?.unifiedSyncDiagnostic&&<div className={`${darkMode?'bg-gray-900':'bg-gray-100'} rounded-xl px-3 py-2 text-[10px] font-mono mb-3 break-all`}>native: {status.unifiedSyncDiagnostic}</div>}
 <div className={`${darkMode?'bg-gray-700/60':'bg-gray-50'} rounded-xl p-3 text-xs mb-3`}><b>每日自動同步：02:00</b><div className="opacity-70 mt-1">街口 90 秒、LINE Pay 120 秒、Pi 90 秒、Google Pay 120 秒；單一來源逾時會跳下一個。整輪超過 8 分鐘會強制停止並回手機桌面，避免螢幕亮整晚。</div></div>
 {night&&night.status!=='NONE'&&<div className={`${nightOk?(darkMode?'bg-green-950':'bg-green-50'):nightWarn?(darkMode?'bg-amber-950':'bg-amber-50'):(darkMode?'bg-red-950':'bg-red-50')} rounded-xl p-3 text-xs mb-3`}><div className="font-bold mb-1">上次 02:00 自動同步：{nightOk?'成功':nightWarn?'部分失敗':'失敗'}</div><div className="opacity-80">{fmt(night.startedAt)} → {fmt(night.finishedAt)}　新增 {night.added||0} 筆</div><div className="grid grid-cols-2 gap-1 mt-2 opacity-80"><div>街口：{resultText(night.jko)}</div><div>LINE：{resultText(night.line)}</div><div>Pi：{resultText(night.pi)}</div><div>Google：{resultText(night.google)}</div></div>{night.summary&&<div className="mt-2 opacity-70">{night.summary}</div>}</div>}
 {!status?.accessibilityEnabled&&<button disabled={busy} onClick={()=>AutoCapture.openAccessibilitySettings()} className={`${buttonClass} mb-2 bg-amber-500 text-white`}>開啟 Pay Helper 無障礙服務</button>}
 <button disabled={busy||!status?.accessibilityEnabled||status?.unifiedSyncRunning} onClick={instantSync} className={`${buttonClass} bg-gradient-to-r from-cyan-600 to-blue-600 text-white text-base py-3`}>{status?.unifiedSyncRunning?'同步進行中…':busy?'啟動中…':'立即同步並寫入消費紀錄'}</button>
 <details className="mt-3"><summary className="text-xs opacity-60 cursor-pointer">診斷 / 手動整理工具</summary><div className="grid grid-cols-1 gap-2 mt-2"><button disabled={busy||status?.unifiedSyncRunning} onClick={autoImport} className={`${buttonClass} ${darkMode?'bg-gray-700':'bg-gray-100'}`}>只整理目前已擷取的交易</button><button disabled={busy} onClick={()=>AutoCapture.diagnoseGoogleWallet()} className={`${buttonClass} ${darkMode?'bg-gray-700':'bg-gray-200'}`}>Google Wallet 診斷</button><button disabled={busy} onClick={exportGoogle} className={`${buttonClass} ${darkMode?'bg-gray-700':'bg-gray-200'}`}>匯出 Google Wallet 診斷 JSON</button></div></details>
 {message&&<div className={`mt-3 text-xs leading-relaxed ${darkMode?'text-gray-300':'text-gray-600'}`}>{message}</div>}<div className="mt-3 text-[10px] opacity-50 leading-relaxed">上次凌晨同步結果會獨立保存，不會因你之後手動同步而被覆蓋。</div></div>;
}
